apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: practice
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: alpine
        command: ["sh", "-c", "echo running db migration && sleep 5"]
      restartPolicy: Never
