apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-plain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HamzaShakeel18/argocd-gitops
    targetRevision: HEAD
    path: argo/manifests/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: practice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
